  import type { Metadata } from "next";
  import { Geist, Geist_Mono } from "next/font/google";
  import "./globals.css";
import { DataProvider } from "@/Context/AppContext";

  const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
  });

  const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
  });

  export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

  export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <html lang="pt-br">
        <head>
          <link rel="shortcut icon" href="https://cdn-icons-png.freepik.com/256/6862/6862037.png?semt=ais_hybrid" type="image/x-icon" />
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <DataProvider> {/* Envolvendo toda a aplicação com o contexto */}
            {children}
          </DataProvider>
        </body>
      </html>
    );
  }
